import Head from 'next/head';
import { FC } from 'react';
import Header from './Header/Header';

interface Layout {
  children: React.ReactNode;
  section?: boolean;
  container?: boolean;
  className?: string;
}

const Layout: FC<Layout> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Monflow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={`main-content`}>
        {children}
      </main>

      <footer>
        Footer
      </footer>
    </>
  );
}

export default Layout;