import Head from 'next/head';
import { FC } from 'react';
import Footer from './Footer/Footer';
import Header from './Header/Header';
import usePlaylist from '@/presentation/hooks/usePlaylist';

interface Layout {
  children: React.ReactNode;
  section?: boolean;
  container?: boolean;
  className?: string;
  hasFooter?: boolean;
}

const Layout: FC<Layout> = ({ children, hasFooter = true }) => {
  // call hook to dispatch playlist everywhere in app
  usePlaylist();

  return (
    <div className='layout is-flex is-flex-direction-column'>
      <Head>
        <title>Monflow</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className="is-flex-grow-1 is-flex-shrink-1">
        {children}
      </main>

      {
        hasFooter && <Footer />
      }
    </div>
  );
}

export default Layout;